[package]
name = "musicbot"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"

[dependencies]
serenity = { version = "0.9.0-rc.0", features = ["voice"] }
tokio = { version = "0.3", features = ["full"] }
